### ISSUE TITLE
Feature Request: Text Editor Find

### ISSUE THREAD

**Issue by flatlinebb** [subhra74/snowflake#10]
One small feature request, more of a nice-to-have:
When opening the find and replace tool in the Text Editor, it would be nice if the Find input field was in focus, so I can start typing what I want to find right away. This is how the find function works in both Chrome and Firefox. Currently, have to click in the Find field at the bottom and then start typing.

**Comment by subhra74** [comment]
This will be fixed in next version

**Comment by subhra74** [comment]
fixed in 1.0.4
