### ISSUE TITLE
Move sites from Snowflake's Site Manager

### ISSUE THREAD

**Issue by iPublicis** [subhra74/snowflake#120]
**Is your feature request related to a problem? Please describe.**
I cannot move a site definition item from one folder to another.

**Describe the solution you'd like**.
Drag and drop site's itens and folders

**Comment by subhra74** [comment]
Thats problem exists in snap version, till it is fixed, please use the other installer: https://github.com/subhra74/snowflake/releases/download/v1.0.4/snowflake-1.0.4-setup-amd64.bin
