### ISSUE TITLE
How to change default text editor to sublime or etc

### ISSUE THREAD

**Issue by JAYATEJAK** [subhra74/snowflake#156]
How can I change default text editor while opening .py files. (without using internal editor)

**Comment by dmissud** [comment]
I agree with that :+1:  Please give the possibility to change the font and the size.
I use a 4k monitor and it's impossible to use you're software.

**Comment by JAYATEJAK** [comment]
> I agree with that  Please give the possibility to change the font and the size.
> I use a 4k monitor and it's impossible to use you're software.
