### ISSUE TITLE
Import-Export function

### ISSUE THREAD

**Issue by karanikn** [subhra74/snowflake#18]
It will be nice to have Import Export functionality.

**Comment by TopperBG** [comment]
Also import from PuTTY sessions

**Comment by NoMaillard** [comment]
i would also be great if it could import WinSCP configurations

**Comment by JeepGuy2175** [comment]
Please also add the ability to import from an unencrypted PuttyCM db file(utf-16 encoded xml file) keeping the folder structures.

We have 50+ server connections and this would let us easily move to snowflake.

**Comment by subhra74** [comment]
winscp and putty import implemented in 1.0.4

**Comment by logix727** [comment]
could we also get import function for mtputty?  I have over 50 connections
