### ISSUE TITLE
the maximum port available is only 32767 should be 65535

### ISSUE THREAD

**Issue by amir-hz** [subhra74/snowflake#24]
I can't connect to my server because the available ports are only 32767 while the server that I have uses port 40000

**Comment by jeb218** [comment]
I am having the same issue, i need support up to 65,535 as well please!!

**Comment by n0nag0n** [comment]
Me too!

**Comment by jkwedar** [comment]
Just FYI, I worked around this by editing the json file.

**Comment by skelley-lscc** [comment]
The SessionInfoPanel.java (in snowflake/components/newsession) uses Short.MAXINT as the maximum value for the spinner control (line 134). Use 65535 as the max value instead.
