### ISSUE TITLE
Make final JAR assembly name carry the version

### ISSUE THREAD

**Issue by cstamas** [subhra74/snowflake#27]
Much better if you know what version you have than just `snowflake.jar` (same is in releases downloads, no version). People will anyway create scripts or desktop shortcuts to start it up

**Comment by subhra74** [comment]
I intentionally removed it, as the installer script for Windows and linux needs to be updated every time. However I have added it back, so version will be appended with the generated jar name

**Comment by subhra74** [comment]
Added changes
