### ISSUE TITLE
Admin rights for Windows installation means: no installation possible

### ISSUE THREAD

**Issue by VonC** [subhra74/snowflake#3]
The one place where I need to connect to SSH servers is in an enterprise environment.

Where I obviously do _not_ have admin rights on my workstation.
Launching snowflake.msi triggers a privilege elevation request.

Is it possible to have a simple archive (zip) for us users to unzip anywhere we want and launch it?

**Comment by subhra74** [comment]
I am planning to release a portable version as well, which can be installed without admin rights.
Also snowflake jar can also be used, if Java 11 is installed on the system.

**Comment by VonC** [comment]
Great! I will test the jar then.

That should be enough for now: no need for this issue to remain open.
