### ISSUE TITLE
In session manager I can't use port above 33000. 

### ISSUE THREAD

**Issue by vilija19** [subhra74/snowflake#36]

**Comment by ocomsoft** [comment]
I just found this also. Why is this?

**Comment by VandalValo** [comment]
Confirmed on Windows. Cannot enter ports higher than 32767.
![image](https://user-images.githubusercontent.com/11087494/73521242-28070100-440e-11ea-9df0-bf4fd65659cf.png)

**Comment by subhra74** [comment]
Its been fixed, but new installer is not created yet.

**Comment by subhra74** [comment]
fixed in 1.0.4

**Comment by vilija19** [comment]
Thanks a lot.
Good work!
