### ISSUE TITLE
Able to connect only on port 22

### ISSUE THREAD

**Issue by JeremyCDP** [subhra74/snowflake#37]
I tried some other ports, but I only can connect on my SSH server using port 22 ( of course, I changed the listening port on my SSH server)

**Comment by infectormp** [comment]
+1

**Comment by azadshaikh** [comment]
I found this tool from techrepublic. Really like this tool. I don't have to use Mobaxterm and Termius anymore. Thank you.

**Comment by subhra74** [comment]
> I tried some other ports, but I only can connect on my SSH server using port 22 ( of course, I changed the listening port on my SSH server)

Ok, will check it

**Comment by miqballharbow** [comment]
i can connect using other port with windows version snowflake

**Comment by KirillChubarov** [comment]
I can't set big number fot SSH port. 40000 eg.

**Comment by subhra74** [comment]
fixed in 1.0.4

**Comment by gabrix73** [comment]
Hi !
I use snowflake-1.0.4-setup-amd64.deb on Debian 11 and i cannot connect on other port than 22.
