### ISSUE TITLE
Create a Zip version instead of MSI installer

### ISSUE THREAD

**Issue by sagarmorakhia** [subhra74/snowflake#39]
Any chance that you can create a zip version of the software so that people without admin rights can also use it?

**Comment by eitch** [comment]
I second this. It would be nicer to just unpack and run, instead of installing stuff.

**Comment by subhra74** [comment]
this will be provided soon, in the meantime the jar can be used

**Comment by eitch** [comment]
Ahh, a JAR is a good alternative, thank you.

**Comment by sagarmorakhia** [comment]
Thanks for the reply @subhra74 
I am not a Java guy so not sure how can I make use of the Jar to use Terminal.

**Comment by subhra74** [comment]
Just install Java 11 or Java 13. Then download the jar and double click to execute it.
