### ISSUE TITLE
Compilation notes?

### ISSUE THREAD

**Issue by richkiz** [subhra74/snowflake#40]
It would be great to include detailed "for dummies" description on how to compile the source so that people could contribute to this promising project.
For example I can tell that there is an issue with this field:
inpPort = new JSpinner(portModel);
Ant it probably needs some parameters set, but before I start messing up with the code I should at least compile the source myself.
But since I have never done any coding with java, I have no idea how to compile the jar file.\
I tried "javac App.java". Got bunch of errors. Not in the mood for digging further :)

**Comment by subhra74** [comment]
Thanks for your suggestion, will add it to read me

**Comment by subhra74** [comment]
Added section for compilation
