### ISSUE TITLE
Adding comma to the port

### ISSUE THREAD

**Issue by euyguner** [subhra74/snowflake#43]
SSH connection cannot be established because of comma adding to the port number.
After 999 it adding comma like 1,000 to the port number.
![Screenshot from 2020-01-31 09-46-30](https://user-images.githubusercontent.com/48209932/73525029-9d72d180-440e-11ea-8e2c-17cd576aea27.png)

**Comment by subhra74** [comment]
The comma does not affect the port value, its just for display and formatting
