### ISSUE TITLE
Feature Request: SSH key management, ENTER key, Putty Sessions

### ISSUE THREAD

**Issue by flatlinebb** [subhra74/snowflake#5]
Thank you for making this software, it looks great and has some really ambitious features. I do wish a few small things would work different or better. 

First, SSH key management is confusing. It allows for creating new keys easily, but not for using existing keys. I wish that in the New Connection window there was a box for the existing SSH public key, so I can use a key I already have for a particular machine. Some of my servers do not allow interactive logon, and I'm having trouble figuring out how to connect to them.

Next, I wish I could just press the ENTER key for some dialog boxes, instead of having to click Yes or OK. I'm already typing something, just accept the input with ENTER. Also, is it more common for the choices to be OK and Cancel, instead of Yes and No, like on the input password pop-up dialog.

Last, I wish I could import my existing Putty sessions. This is a big one, as I have a lot of sessions. Combined with the awkward SSH key management, it's a pain to add new sites. Also support for Pageant or Putty keys would be awesome too.

Again, thank you for your hard work on this software and I'm looking forward to future improvements.

**Comment by subhra74** [comment]
Thanks for sharing your feedback.

You can use key based authentication by simply selecting the location of you ssh key in new connection dialog. There is an option for providing private key file.
Also for adding to servers authorized_key file, you can just copy the public key contents and paste it in the "authorized keys" section on "Server" tab.

You are correct about the ENTER key, that I will implement in next version, along with import of existing putty and winscp session.

**Comment by flatlinebb** [comment]
I feel so stupid. I never thought to scroll down in the New Connection
dialog. Sure, enough there is a field for a private key. Thank you for
showing me the way. I use enlarged DPI in Windows, so sometimes dialog
boxes do not look as intended.

I have one more small suggestion: a way to export sites and settings, so I
can setup snowflake on another computer, without having to do everything
from scratch.

And I have a question about the option in Settings: "Use Putty-like
copy/paste for terminal" - what exactly does this option enable? I have it
checked and pasting with right-mouse button or Shift-Insert does not work,
like it works in Putty. (Right-click, then click on Paste does work, but
that's not Putty-like behavior).

And thank you for taking my suggestions, and planning to implement them in
future versions. Now I'm really excited to be part of your great project
and help spread the word about it.

**Comment by subhra74** [comment]
fixed in 1.0.4
