### ISSUE TITLE
Feature request: Proxy connection like Putty

### ISSUE THREAD

**Issue by ananth-iyer** [subhra74/snowflake#67]
**Is your feature request related to a problem? Please describe.**
Add **Proxy connection** setting in the New Connection pop up like Putty:

**Describe the solution you'd like**
Please review the attached screenshot of Putty application:
![2020_02_03_Selection_02](https://user-images.githubusercontent.com/24892273/73631620-8b4b9a00-467f-11ea-8676-5c97610cf7d2.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Add all the fields from the Proxy screen to the New Connection popup

**Comment by subhra74** [comment]
this has been fixed and committed. however new release has to be created with installer
