### ISSUE TITLE
Upload file on save in external text editor

### ISSUE THREAD

**Issue by gromdron** [subhra74/snowflake#69]
Hello.

When i opening file in internal text editor and save, all changes will save in file correctly.
When open file in external text editor, saved file in this editor not upload changes to remote server.

Сan I force snowflake to load changes to this file when saving in an external editor?

**Comment by jessegyger** [comment]
I second this. I'm used to WinSCP when you open a file and save it, it automatically uploads it so the changes are immediate. This software could be my daily driver if it had this feature.  The internal editor functions this way but can't figure out how to make the internal text editor the default.

**Comment by subhra74** [comment]
As off now if you select the option 

> open with default editor

, changes are monitored and uploaded accordingly

**Comment by gromdron** [comment]
Sorry, but if i select this option, windows can't find default editor.

In my system all files with .php extension marked as Sublime Text 3. If i open file with .php ext, file correctly open and save with sublime. This feature correctly work in WinSCP, but not working with Snowflake.
