### ISSUE TITLE
Prompted for passwords too often

### ISSUE THREAD

**Issue by UserHIJ** [subhra74/snowflake#73]
When I setup an ssh connection I give it a user id and password. Login ensues. 
when I go to the terminal tab I'm asked again. when I go to the other modules, I'm intermittently asked. It's a little infuriating.

**Comment by subhra74** [comment]
fixed in 1.0.4

**Comment by VinistoisR** [comment]
I'm getting this issue on 1.04 much more than 1.03.  I use 2FA which is extra annoying, it asks for a 2fa code first, then the password, then 2fa again.   It does this each time going from module to module.
