### ISSUE TITLE
Unable to type in port number

### ISSUE THREAD

**Issue by beto-p** [subhra74/snowflake#81]
Linux or windows version, i can not type in the port number on go to next field without it defaulting to port 22, when most ssh connections use port 22 we use a 5 digit code for some of the servers. 

I am able to use arrows up and down but takes a long time trying to reach port 56000.

Is this intentional or bug? would be great to just be able to type it in.

**Comment by ChaosZero112** [comment]
Just confirming that I can type in the port number on Windows (build 1903, 18362.592), both on v1.0.3 and v1.0.4.

**Comment by beto-p** [comment]
[Video recording.zip](https://github.com/subhra74/snowflake/files/4157328/Video.recording.zip)

here is a  video of how i cant and some how at the end i was able to change it and it changed after pressing tab which is the same key i pressed including the enter key and kept doing the same thing and it did not change.

using windows 10 1903 and also tested on ubuntu 19.04

**Comment by vicdemuth** [comment]
I have the same issue. On Linux, you can edit the saved config file directly to alter the port No. In my case there has been created a snowflake-ssh directory off my home when first run. The config file sits inside it as session store.json.
Hope this helps until the devs can get to the bottom of it.

**Comment by subhra74** [comment]
The issue has been fixed already, however the installers has not been released yet.

**Comment by subhra74** [comment]
> Linux or windows version, i can not type in the port number on go to next field without it defaulting to port 22, when most ssh connections use port 22 we use a 5 digit code for some of the servers.
> 
> I am able to use arrows up and down but takes a long time trying to reach port 56000.
> 
> Is this intentional or bug? would be great to just be able to type it in.

You can edit it, just type in the port number. however it wont allow higher than 32727 for now. (bug which is fixed but not deployed yet)

**Comment by subhra74** [comment]
this issue is fixed in 1.0.4
