### ISSUE TITLE
Allow users to drag-&-drop the sites in session manager

### ISSUE THREAD

**Issue by jkwedar** [subhra74/snowflake#82]
Allow users to drag-&-drop the sites in session manager.

I like to organize the connections in the session manager into folders, there doesn't seem to be a way to drag them into folders so i am forced to recreate them in the folder. Not the end of the world but would be less painful to either drag+drop or copy+paste.

**Comment by subhra74** [comment]
implemented in 1.0.4

**Comment by VinistoisR** [comment]
this is great.  Except I took my folder with all my sites and tried to drag it up to make it a new root folder.  They all disappeared.  Can you not have another root folder?
