### ISSUE TITLE
DarkTheme only availaible in the Terminal.

### ISSUE THREAD

**Issue by Ethnical** [subhra74/snowflake#9]
Hello guys, 
Nice Work probably the best ssh client i ever tested for a while. But there is one thing when you work lately is to have a DarkTheme in all the application. 
The DarkTheme activated only in the Terminal

Thx for your work !

**Comment by subhra74** [comment]
Dark theme will be there in future

**Comment by GiorgosK** [comment]
Real good job to the team.
Definetelly a Dark theme would be needed as the choice of contrast on white theme actually hurts my eyes.

Thanks in advance and keep up the good work.

**Comment by DevCharly** [comment]
If you guys are looking for a dark Swing L&F,
you could try FlatLaf (https://github.com/JFormDesigner/FlatLaf).
It comes with dark and light themes and scales on HiDPI screens.

**Comment by snukkums** [comment]
Is there a plan to add dark mode to the launch page before you open a terminal?

**Comment by KaKi87** [comment]
@subhra74 In #139 you said :
> Its implemented but yet to be released

What's preventing it from being released, is there anything that can be done to help making it happen ?

**Comment by eliaharm** [comment]
Hello,
Could you please add support for HiDPI, or is there some workaround? 
thx

**Comment by KaKi87** [comment]
@eliaharm HiDPI user here (3160x2160 15.6"), no issue.

**Comment by eliaharm** [comment]
Hi @KaKi87 I am running fedora linux 34 with 2880x1620 on 15" display and the fonts are tiny... 
Can I configure larger fonts or HiDPI compatibility?

**Comment by KaKi87** [comment]
Well, HiDPI on Linux is messy everywhere for everything. I know it's Microsoft & NVidia's fault in the first place, but still, I'm running KDE Neon under Wayland on the very same laptop, and there are lots and lots of bugs.

**Comment by alexisraelmtz** [comment]
What happen with the "coming soon" dark mode? We are going blind with that insane ultra white, please release the dark mode. We would all appreciate it big time. Thanks in advance!!!!!!

**Comment by arteteco** [comment]
Any news on this? It would be greatly appreciated by a lot of people I'm sure!

**Comment by alexisraelmtz** [comment]
For those that haven't yet tried it. I recommend 110% the "[Dark Reader](https://darkreader.org/)" open-source extension for all browsers, it works like a charm and outputs exactly what I was looking for when I originally wanted to find about the dark mode update for Snowflake. 
Thanks for all the hard work! Kudos to the Snowflake @Team.
